### PR TITLE
Switch TypeDoc to file mode

### PR DESCRIPTION
**Pull request by rmainwork**
Submodules are currently broken in TypeDoc (as-of TypeDoc v`0.14`). This appears to be because of a change made by TypeDoc to their underlying API. More information in: christopherthielen/typedoc-plugin-external-module-name#332. That being the case, using file mode at least cleans up the output a little and makes it easier to until submodules can be used.

This PR aims to clean up the organization of documented objects a little so that this:

image

Ends up looking like this:

image

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality
      to change)

## Checklist:

- [x] I have run `eslint` on the code
- [x] I have added JSDoc for all of my code (where applicable)
- [ ] I have added tests to cover my changes.

## Priority:
- [x] Normal 
- [ ] High 

## Related Issues:

Provides a (partial) work-around for #17

### CODE REVIEW

**Review by jonseitz — CHANGES_REQUESTED** [review]
This change itself is fine, but, as we discovered this morning, there is a bug with the current documentation when deployed to `gh-pages`. It turns out that's because [GitHub expects `gh-pages` to use jekyll](https://github.com/TypeStrong/typedoc/issues/362), where files that start with `_` aren't compiled by default. This shouldn't be a problem with `"mode": "file"` since the files no longer start with `_`, but to be on  the safe side we should probably use the solution from the github issue and create a `.nojekyll` file in the docs directory AFTER the docs have been created. 

I'd suggest the following change in `.travis.yml`: 

```diff
--- a/.travis.yml
+++ b/.travis.yml
@@ -18,7 +18,9 @@ jobs:
       - npm run test
       - npm run codecov
     - stage: documentation
-      script: npm run docs
+      script:
+      - npm run docs
+      - touch ./docs/.nojekyll
       deploy:
         provider: pages
         skip_cleanup: true
```

**Comment by rmainwork** [comment]
I'm not so sure we need to do this.

I configured [this deployment](https://github.com/joshmarinacci/node-pureimage/blob/master/.travis.yml) to [GH Pages](http://joshmarinacci.github.io/node-pureimage/) a while ago without `.nojekylll`. I think you can configure this.

**Comment by jonseitz** [comment]
Strictly speaking it's not required to deploy on github pages, but that's the reason why the links in the current deployed pages at [https://seas-computing.github.io/react-boilerplate/](https://seas-computing.github.io/react-boilerplate/) aren't working. I don't think it will continue to be an issue with the mode changed, but I'd rather change this now to avoid running into this bug again if TypeDoc adds `_` to start of other filenames in the future.

(There's also [a Typedoc plugin](https://github.com/bluelovers/typedoc-plugin-nojekyll) to do the same thing, but I'd prefer not to add extra dependencies for something this minor.)

**Comment by rmainwork** [comment]
I was trying to figure out why node-pureimage didn't require a `.nojekyl` file. Turns out that the file/folder names don't begin with an underscore. I guess that would be why.

Addressed in 77593d7b5b4d5212867bc7db83ed2aa0a22a511d

**Review by jonseitz — APPROVED** [review]
Yeah, it's kind of a weird that that's a "feature," but easy enough to fix. 

Anyway, this all looks good now. Feel free to merge.

**Pull request merged**
